### ISSUE TITLE
Installing the pyrouge on Microsoft Windows

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [bheinzerling/pyrouge#12]
FYI, I've had many issues to install the Python package pyrouge on Microsoft Windows, so I wrote a tutorial: 
[How to install the  pyrouge on Microsoft Windows?](https://stackoverflow.com/q/47045436/395857)

**Comment by bheinzerling** [comment]
Thanks a lot, this looks really useful!
I added a link to your guide in the readme.
