### ISSUE TITLE
location of ROUGE binary

### ISSUE THREAD

**Issue by clayms** [bheinzerling/pyrouge#18]
when installing on a RHEL (fedora varient Linux) system with `pip3.6 install pyrouge --user` installs pyrouge in the typical python package location for users `/home/user.name/.local/lib/python3.6/site-packages/`.

Running `pyrouge_set_rouge_path /home/user.name/.local/lib/python3.6/site-packages/pyrouge` from the shell, or `r = Rouge155('/home/user.name/.local/lib/python3.6/site-packages/pyrouge')` from python throws the following error.

```
Traceback (most recent call last):
  File "/home/user.name/.local/bin/pyrouge_set_rouge_path", line 18, in <module>
    main()
  File "/home/user.name/.local/bin/pyrouge_set_rouge_path", line 15, in main
    Rouge155(args.home_dir)
  File "/home/user.name/.local/lib/python3.6/site-packages/pyrouge/Rouge155.py", line 88, in __init__
    self.__set_rouge_dir(rouge_dir)
  File "/home/user.name/.local/lib/python3.6/site-packages/pyrouge/Rouge155.py", line 412, in __set_rouge_dir
    "/path/to/rouge/home.".format(self._bin_path))
Exception: ROUGE binary not found at /home/user.name/.local/lib/python3.6/site-packages/pyrouge/ROUGE-1.5.5.pl. Please set the correct path by running pyrouge_set_rouge_path /path/to/rouge/home.
```

Where are the pyrouge binaries?

**Comment by bheinzerling** [comment]
You need to download the original ROUGE-1.5.5.pl perl script and point pyrouge to its location.

The original script used to be available from the author's website, but this seems to be down now. There are some copies floating around, e.g. https://github.com/andersjo/pyrouge/blob/master/tools/ROUGE-1.5.5/ROUGE-1.5.5.pl

**Comment by clayms** [comment]
thanks, just figured that out.

https://github.com/andersjo/pyrouge.git
