### ISSUE TITLE
Rouge-L result is very low

### ISSUE THREAD

**Issue by hanghang2333** [bheinzerling/pyrouge#24]
I am working on a model of a text summary. For the output of the model, the test is performed using pyrouge. The test results show that the rouge-1 and rouge2 indicators are normal and consistent with the effect of the paper. However, the results of rouge-L differ greatly from the results of the paper. What is doubtful is how the rouge-L is calculated. What could be the cause of this?

**Comment by ShirleyHan6** [comment]
Hi Hanghang, 

Did you figure out about the reason?

**Comment by astariul** [comment]
Any update on this ? @ShirleyHan6 @hanghang2333 

How much the ROUGE-L results differ ?
