### ISSUE TITLE
Unittests fail

### ISSUE THREAD

**Issue by frankdiehl** [bheinzerling/pyrouge#7]
Hi, I've installed pyrouge on my Mac running it within a virtual environment under Python 2.7.13. After activating the virtual environment and calling   pyrouge_set_rouge_path <path to ROUGE-1.5.5.pl folder>  I run the unittests with   python -m pyrouge.test. However some of them fail saying:

======================================================================
FAIL: test_config_file (pyrouge.tests.Rouge155_test.PyrougeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/frank/Projects/ve.pyrouge/lib/python2.7/site-packages/pyrouge/tests/Rouge155_test.py", line 154, in test_config_file
    add_data_path("ROUGE-test_11.xml")))
AssertionError: False is not true

======================================================================
FAIL: test_evaluation (pyrouge.tests.Rouge155_test.PyrougeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/frank/Projects/ve.pyrouge/lib/python2.7/site-packages/pyrouge/tests/Rouge155_test.py", line 172, in test_evaluation
    self.assertEqual(pyrouge_output, orig_rouge_output)
AssertionError: u'---------------------------------------------\n11 ROUGE-1 Average_R: 0.22651 ( [truncated]... != u'---------------------------------------------\n11 ROUGE-1 Average_R: 0.77650 ( [truncated]...
Diff is 5949 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_rouge_for_plain_text (pyrouge.tests.Rouge155_test.PyrougeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/frank/Projects/ve.pyrouge/lib/python2.7/site-packages/pyrouge/tests/Rouge155_test.py", line 192, in test_rouge_for_plain_text
    self.assertEqual(pyrouge_output, orig_rouge_output)
AssertionError: u'---------------------------------------------\n1 ROUGE-1 Average_R: 0.40054 (9 [truncated]... != u'---------------------------------------------\n1 ROUGE-1 Average_R: 0.61336 (9 [truncated]...
Diff is 6253 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_write_config (pyrouge.tests.Rouge155_test.PyrougeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/frank/Projects/ve.pyrouge/lib/python2.7/site-packages/pyrouge/tests/Rouge155_test.py", line 211, in test_write_config
    self.assertTrue(xml_equal(config_file, target_xml))
AssertionError: False is not true

Until now I wasn't able to identify the reason for this issue. Any help is highly appreciated.

**Comment by bheinzerling** [comment]
Can you please try if tests pass with the latest version (which is not on pypi yet):

`git clone https://github.com/bheinzerling/pyrouge`
`cd pyrouge`
`python setup.py install`
`python -m pyrouge.test`

**Comment by frankdiehl** [comment]
Hi, using the latest pyrouge version from GitHub instead pypi worked, i.e. the unit test passed successfully. I though had to add 

pyrouge_set_rouge_path  <path to ROUGE-1.5.5> 

before calling the test. 

Thanks a lot for your help!

**Comment by rylanchiu** [comment]
Got this error : `IOError: [Errno 2] No such file or directory: u'/home/sunny/.pyrouge/settings.ini'`. Could you please help me with this? Thx!

**Comment by bheinzerling** [comment]
Did you run this command after installing?

`pyrouge_set_rouge_path /absolute/path/to/ROUGE-1.5.5/directory`

If saving the rouge path using this script doesn't work on your system, you can also supply the rouge path at runtime:

`r = Rouge155('/absolute/path/to/ROUGE-1.5.5/directory'`

**Comment by yuanmingchen** [comment]
非常感谢！帮我解决了一个大麻烦！
`git clone https://github.com/bheinzerling/pyrouge`
`cd pyrouge`
`python setup.py install`
`pyrouge_set_rouge_path your_rouge_path/ROUGE-1.5.5`
`python -m pyrouge.test`

**Comment by Santosh-Gupta** [comment]
I am getting this error too, in Google colab

"FileNotFoundError: [Errno 2] No such file or directory: '/root/.pyrouge/settings.ini'"

Here is what I tried

```
!pip install pyrouge
!pip show pyrouge
```

output shows it's installed in 

> Location: /usr/local/lib/python3.6/dist-packages

So I tried

`!pyrouge_set_rouge_path '/usr/local/lib/python3.6/dist-packages/pyrouge/'`

Output was

```
2019-07-27 01:20:55,294 [MainThread  ] [INFO ]  Set ROUGE home directory to /usr/local/lib/python3.6/dist-packages/pyrouge/.
Traceback (most recent call last):
  File "/usr/local/bin/pyrouge_set_rouge_path", line 18, in <module>
    main()
  File "/usr/local/bin/pyrouge_set_rouge_path", line 15, in main
    Rouge155(args.home_dir)
  File "/usr/local/lib/python3.6/dist-packages/pyrouge/Rouge155.py", line 88, in __init__
    self.__set_rouge_dir(rouge_dir)
  File "/usr/local/lib/python3.6/dist-packages/pyrouge/Rouge155.py", line 407, in __set_rouge_dir
    self.data_dir = os.path.join(self._home_dir, 'data')
  File "/usr/local/lib/python3.6/dist-packages/pyrouge/Rouge155.py", line 543, in fset
    verify_dir(path, dir_name)
  File "/usr/local/lib/python3.6/dist-packages/pyrouge/utils/file_utils.py", line 87, in verify_dir
    raise Exception(msg)
Exception: Cannot set data directory because the path /usr/local/lib/python3.6/dist-packages/pyrouge/data does not exist.
```

So then I tried

`!pyrouge_set_rouge_path '/usr/local/lib/python3.6/dist-packages/pyrouge/tests'`

Then got this error

```
2019-07-27 01:21:16,011 [MainThread  ] [INFO ]  Set ROUGE home directory to /usr/local/lib/python3.6/dist-packages/pyrouge/tests.
Traceback (most recent call last):
  File "/usr/local/bin/pyrouge_set_rouge_path", line 18, in <module>
    main()
  File "/usr/local/bin/pyrouge_set_rouge_path", line 15, in main
    Rouge155(args.home_dir)
  File "/usr/local/lib/python3.6/dist-packages/pyrouge/Rouge155.py", line 88, in __init__
    self.__set_rouge_dir(rouge_dir)
  File "/usr/local/lib/python3.6/dist-packages/pyrouge/Rouge155.py", line 412, in __set_rouge_dirsc
    "/path/to/rouge/home.".format(self._bin_path))
Exception: ROUGE binary not found at /usr/local/lib/python3.6/dist-packages/pyrouge/tests/ROUGE-1.5.5.pl. Please set the correct path by running pyrouge_set_rouge_path /path/to/rouge/home.
```

Here is a direct public link to the notebook I am working on 

https://colab.research.google.com/drive/1vKYu-RPR5FJ1ZukTC7JDcfDYK6bm45eq

**Comment by crystina-z** [comment]
hi I met this errors also, trying to solve the problem with: 

> 非常感谢！帮我解决了一个大麻烦！
> `git clone https://github.com/bheinzerling/pyrouge`
> `cd pyrouge`
> `python setup.py install`
> `pyrouge_set_rouge_path your_rouge_path/ROUGE-1.5.5`
> `python -m pyrouge.test`

yet cannot find where is `ROUGE-1.5.5`? looking for suggestions and thanks!

**Comment by RakshaAg** [comment]
Please help

**Comment by stellaywu** [comment]
Rouge-1.5.5 https://github.com/andersjo/pyrouge/tree/master/tools/ROUGE-1.5.5 repos is already achieved. is there another way to install it? Thanks!

**Comment by stellaywu** [comment]
can't find ROUGE-1.5.5 either, is this the official link? it's out of maintenance already https://github.com/andersjo/pyrouge/tree/master/tools/ROUGE-1.5.5

**Comment by soid** [comment]
I used pip for installing pyrouge, and I solved it like this:
```
$ pip3 show pyrouge
...
Location: /opt/homebrew/lib/python3.10/site-packages
...
$ find /opt/homebrew/lib/python3.10/site-packages -name ROUGE-1.5.5.pl
/opt/homebrew/lib/python3.10/site-packages/rouge_metric/RELEASE-1.5.5/ROUGE-1.5.5.pl
$ pyrouge_set_rouge_path /opt/homebrew/lib/python3.10/site-packages/rouge_metric/RELEASE-1.5.5/ROUGE-1.5.5.pl

```
